image: Ubuntu2004

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - sudo apt-get -qq update
  - sudo apt-get install wait-for-it > /dev/null
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo iptables -I INPUT -m conntrack --ctstate INVALID -j DROP
  - docker-compose up --build -d
  - docker ps

build_script:
  - wait-for-it localhost:9999 -t 100
  - netstat -na | grep "9999"
  # - sleep 15
  - curl --show-error -X GET 'http://localhost:9999/api/cards'
